---
- hosts: localhost
  become: true
  gather_facts: no
  connection: local

  tasks:
  - set_fact: BUILD_ID="{{ lookup('env','BUILD_ID') }}"
  - name: Build New Docker Image
    docker_image:
      path: ../tomcat
      name: schogini/tomcat
      tag: pipeline-{{BUILD_ID}}
    register: docker_build
  - debug:
      msg: "Docker Image Build Done: schogini/tomcat:pipeline-{{BUILD_ID}}"
